// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WS_VINOTRIP.Models.EntityFramework;

#nullable disable

namespace WS_VINOTRIP.Migrations
{
    [DbContext(typeof(VinotripDBContext))]
    [Migration("20230328091902_CreationBDVinotrip")]
    partial class CreationBDVinotrip
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Adresse", b =>
                {
                    b.Property<int>("AdresseId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ads_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AdresseId"));

                    b.Property<int>("Cp")
                        .HasColumnType("char(5)")
                        .HasColumnName("ads_cp");

                    b.Property<string>("Pays")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ads_pays");

                    b.Property<string>("Rue1")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ads_rue1");

                    b.Property<string>("Rue2")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ads_rue2");

                    b.Property<string>("Ville")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ads_ville");

                    b.HasKey("AdresseId")
                        .HasName("pk_ads");

                    b.ToTable("t_e_adresse_ads");

                    b.HasCheckConstraint("ck_ads_rue1_rue2", "ads_rue1 <> ads_rue2");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Avis", b =>
                {
                    b.Property<int>("AvisId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("avi_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AvisId"));

                    b.Property<DateTime>("DateAvis")
                        .HasColumnType("date")
                        .HasColumnName("avi_dateavis");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("avi_description");

                    b.Property<int>("Note")
                        .HasColumnType("integer")
                        .HasColumnName("avi_note");

                    b.Property<int>("PersonneId")
                        .HasColumnType("integer")
                        .HasColumnName("prs_id");

                    b.Property<string>("Reponse")
                        .HasColumnType("text")
                        .HasColumnName("avi_reponse");

                    b.Property<int>("SejourId")
                        .HasColumnType("integer")
                        .HasColumnName("sjr_id");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("avi_titre");

                    b.HasKey("AvisId")
                        .HasName("pk_avi");

                    b.HasIndex("PersonneId");

                    b.HasIndex("SejourId");

                    b.ToTable("t_e_avis_avi");

                    b.HasCheckConstraint("ck_avi_note", "avi_note between 1 and 5");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.BonCadeau", b =>
                {
                    b.Property<int>("BonCadeauId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("bcd_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("BonCadeauId"));

                    b.Property<string>("CodeReduction")
                        .IsRequired()
                        .HasColumnType("char(8)")
                        .HasColumnName("bcd_codereduction");

                    b.Property<DateTime>("DateExpirationBon")
                        .HasColumnType("date")
                        .HasColumnName("bcd_dateexpirationbon");

                    b.HasKey("BonCadeauId")
                        .HasName("pk_bcd");

                    b.HasAlternateKey("CodeReduction")
                        .HasName("uq_bcd_codereduction");

                    b.ToTable("t_e_boncadeau_bcd");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.CatParticipant", b =>
                {
                    b.Property<int>("CatParticipantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cpp_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CatParticipantId"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("vgb_titre");

                    b.Property<int>("LienId")
                        .HasColumnType("integer")
                        .HasColumnName("len_id");

                    b.HasKey("CatParticipantId")
                        .HasName("pk_cpp");

                    b.HasIndex("LienId");

                    b.ToTable("t_e_catparticipant_cpp");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.CatSejour", b =>
                {
                    b.Property<int>("CatSejourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("csj_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CatSejourId"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("csj_libelle");

                    b.Property<int>("LienId")
                        .HasColumnType("integer")
                        .HasColumnName("len_id");

                    b.HasKey("CatSejourId")
                        .HasName("pk_csj");

                    b.HasIndex("LienId");

                    b.ToTable("t_e_catsejour_csj");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.CatVignoble", b =>
                {
                    b.Property<int>("CatVignobleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cvg_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CatVignobleId"));

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("cvg_description");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("cvg_libelle");

                    b.HasKey("CatVignobleId")
                        .HasName("pk_cvg");

                    b.ToTable("t_e_catvignoble_cvg");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.ChequeCadeau", b =>
                {
                    b.Property<int>("BonCadeauId")
                        .HasColumnType("integer")
                        .HasColumnName("bcd_id");

                    b.Property<int>("Montant")
                        .HasColumnType("integer")
                        .HasColumnName("cqc_montant");

                    b.HasKey("BonCadeauId")
                        .HasName("pk_cqc");

                    b.ToTable("t_e_chequecadeau_cqc");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Commande", b =>
                {
                    b.Property<int>("CommandeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("cmd_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CommandeId"));

                    b.Property<DateTime>("DateFacture")
                        .HasColumnType("date")
                        .HasColumnName("cmd_datefacture");

                    b.Property<int?>("MontantReduction")
                        .HasColumnType("integer")
                        .HasColumnName("cmd_montantreduction");

                    b.Property<int>("PersonneId")
                        .HasColumnType("integer")
                        .HasColumnName("prs_id");

                    b.HasKey("CommandeId")
                        .HasName("pk_cmd");

                    b.HasIndex("PersonneId");

                    b.ToTable("t_e_commande_cmd");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Comporte", b =>
                {
                    b.Property<int>("SejourId")
                        .HasColumnType("integer")
                        .HasColumnName("sjr_id");

                    b.Property<int>("CatParticipantId")
                        .HasColumnType("integer")
                        .HasColumnName("cpp_id");

                    b.HasKey("SejourId", "CatParticipantId")
                        .HasName("pk_cpt");

                    b.HasIndex("CatParticipantId");

                    b.ToTable("t_j_comporte_cpt");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.CompteCarte", b =>
                {
                    b.Property<int>("PersonneId")
                        .HasColumnType("integer")
                        .HasColumnName("ctl_id");

                    b.Property<int>("CarteId")
                        .HasColumnType("integer")
                        .HasColumnName("rcb_id");

                    b.HasKey("PersonneId", "CarteId")
                        .HasName("pk_cpc");

                    b.HasIndex("CarteId");

                    b.ToTable("t_e_comptecarte_cpc");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Concerne", b =>
                {
                    b.Property<int>("EtapeId")
                        .HasColumnType("integer")
                        .HasColumnName("etp_id");

                    b.Property<int>("ElementId")
                        .HasColumnType("integer")
                        .HasColumnName("ele_id");

                    b.Property<TimeOnly?>("Horaire")
                        .IsRequired()
                        .HasColumnType("time")
                        .HasColumnName("ccr_horaire");

                    b.HasKey("EtapeId", "ElementId")
                        .HasName("pk_ccr");

                    b.HasIndex("ElementId");

                    b.ToTable("t_j_concerne_ccr");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Contient", b =>
                {
                    b.Property<int>("LienId")
                        .HasColumnType("integer")
                        .HasColumnName("len_id");

                    b.Property<int>("ElementId")
                        .HasColumnType("integer")
                        .HasColumnName("ele_id");

                    b.HasKey("LienId", "ElementId")
                        .HasName("pk_ctn");

                    b.HasIndex("ElementId");

                    b.ToTable("t_j_contient_ctn");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.ElementEtape", b =>
                {
                    b.Property<int>("ElementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ele_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ElementId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ele_description");

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("ele_libelle");

                    b.Property<int>("PersonneId")
                        .HasColumnType("integer")
                        .HasColumnName("prs_id");

                    b.Property<int?>("TypeElementId")
                        .HasColumnType("integer")
                        .HasColumnName("tpe_id");

                    b.HasKey("ElementId")
                        .HasName("pk_ele");

                    b.HasIndex("PersonneId");

                    b.HasIndex("TypeElementId");

                    b.ToTable("t_e_elementetape_ele");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.ElementVignoble", b =>
                {
                    b.Property<int>("ElementVignobleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("evg_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ElementVignobleId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("evg_description");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(70)
                        .HasColumnType("character varying(70)")
                        .HasColumnName("evg_titre");

                    b.Property<int>("VignobleId")
                        .HasColumnType("integer")
                        .HasColumnName("vgb_id");

                    b.HasKey("ElementVignobleId")
                        .HasName("pk_evg");

                    b.HasIndex("VignobleId");

                    b.ToTable("t_e_elementvignoble_evg");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Est_facturee", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("integer")
                        .HasColumnName("rsv_id");

                    b.Property<int>("AdresseId")
                        .HasColumnType("integer")
                        .HasColumnName("ads_id");

                    b.HasKey("ReservationId", "AdresseId")
                        .HasName("pk_efc");

                    b.HasIndex("AdresseId");

                    b.ToTable("t_j_est_facturee_efc");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Etape", b =>
                {
                    b.Property<int>("EtapeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("etp_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("EtapeId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("etp_description");

                    b.Property<int?>("SejourId")
                        .HasColumnType("integer")
                        .HasColumnName("sjr_id");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("etp_titre");

                    b.HasKey("EtapeId")
                        .HasName("pk_etp");

                    b.HasIndex("SejourId");

                    b.ToTable("t_e_etape_etp");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Favori", b =>
                {
                    b.Property<int>("SejourId")
                        .HasColumnType("integer")
                        .HasColumnName("sjr_id");

                    b.Property<int>("PersonneId")
                        .HasColumnType("integer")
                        .HasColumnName("prs_id");

                    b.HasKey("SejourId", "PersonneId")
                        .HasName("pk_fav");

                    b.HasIndex("PersonneId");

                    b.ToTable("t_j_favori_fav");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.HistoriqueCadeau", b =>
                {
                    b.Property<int>("PersonneId")
                        .HasColumnType("integer")
                        .HasColumnName("ctl_id");

                    b.Property<int>("BonCadeauId")
                        .HasColumnType("integer")
                        .HasColumnName("bcd_id");

                    b.Property<string>("TypeCadeau")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("htc_typecadeau");

                    b.HasKey("PersonneId", "BonCadeauId")
                        .HasName("pk_htc");

                    b.HasIndex("BonCadeauId");

                    b.ToTable("t_e_historiquecadeau_htc");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Lien", b =>
                {
                    b.Property<int>("LienId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("len_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("LienId"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("len_type");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("len_url");

                    b.HasKey("LienId")
                        .HasName("pk_len");

                    b.ToTable("t_e_lien_len");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.LienAvis", b =>
                {
                    b.Property<int>("LienId")
                        .HasColumnType("integer")
                        .HasColumnName("len_id");

                    b.Property<int>("AvisId")
                        .HasColumnType("integer")
                        .HasColumnName("avi_id");

                    b.HasKey("LienId", "AvisId")
                        .HasName("pk_lav");

                    b.HasIndex("AvisId");

                    b.ToTable("t_j_lienavis_lav");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.LienElementVignoble", b =>
                {
                    b.Property<int>("LienId")
                        .HasColumnType("integer")
                        .HasColumnName("len_id");

                    b.Property<int>("ElementVignobleId")
                        .HasColumnType("integer")
                        .HasColumnName("evg_id");

                    b.HasKey("LienId", "ElementVignobleId")
                        .HasName("pk_lev");

                    b.HasIndex("ElementVignobleId");

                    b.ToTable("t_j_lienelementvignoble_lev");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.LienEtape", b =>
                {
                    b.Property<int>("LienId")
                        .HasColumnType("integer")
                        .HasColumnName("len_id");

                    b.Property<int>("EtapeId")
                        .HasColumnType("integer")
                        .HasColumnName("etp_id");

                    b.HasKey("LienId", "EtapeId")
                        .HasName("pk_lep");

                    b.HasIndex("EtapeId");

                    b.ToTable("t_j_lienetape_lep");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.LienRouteDesVins", b =>
                {
                    b.Property<int>("LienId")
                        .HasColumnType("integer")
                        .HasColumnName("len_id");

                    b.Property<int>("RouteDesVinsId")
                        .HasColumnType("integer")
                        .HasColumnName("rdv_id");

                    b.HasKey("LienId", "RouteDesVinsId")
                        .HasName("pk_lrv");

                    b.HasIndex("RouteDesVinsId");

                    b.ToTable("t_j_lienroutedesvins_lrv");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.LienSejour", b =>
                {
                    b.Property<int>("LienId")
                        .HasColumnType("integer")
                        .HasColumnName("len_id");

                    b.Property<int>("SejourId")
                        .HasColumnType("integer")
                        .HasColumnName("sjr_id");

                    b.HasKey("LienId", "SejourId")
                        .HasName("pk_lsj");

                    b.HasIndex("SejourId");

                    b.ToTable("t_j_liensejour_lsj");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Panier", b =>
                {
                    b.Property<int>("SejourId")
                        .HasColumnType("integer")
                        .HasColumnName("sjr_id");

                    b.Property<int>("PersonneId")
                        .HasColumnType("integer")
                        .HasColumnName("prs_id");

                    b.Property<bool>("Offert")
                        .HasColumnType("boolean")
                        .HasColumnName("pnr_offert");

                    b.Property<DateTime>("DateSejour")
                        .HasColumnType("date")
                        .HasColumnName("pnr_datesejour");

                    b.Property<int>("NbAdultes")
                        .HasColumnType("integer")
                        .HasColumnName("pnr_nbadultes");

                    b.Property<int>("NbChambres")
                        .HasColumnType("integer")
                        .HasColumnName("pnr_nbchambres");

                    b.Property<int>("NbEnfants")
                        .HasColumnType("integer")
                        .HasColumnName("pnr_nbenfants");

                    b.Property<decimal>("PrixTotal")
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("pnr_prixtotal");

                    b.HasKey("SejourId", "PersonneId", "Offert")
                        .HasName("pk_pnr");

                    b.HasIndex("PersonneId");

                    b.ToTable("t_e_panier_pnr");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Partenaire", b =>
                {
                    b.Property<int>("PersonneId")
                        .HasColumnType("integer")
                        .HasColumnName("prs_id");

                    b.Property<string>("Tel")
                        .HasColumnType("char(10)")
                        .HasColumnName("ptn_tel");

                    b.HasKey("PersonneId")
                        .HasName("pk_ptn");

                    b.ToTable("t_e_partenaire_ptn");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.PartenaireActivite", b =>
                {
                    b.Property<int>("PersonneId")
                        .HasColumnType("integer")
                        .HasColumnName("ptn_id");

                    b.Property<string>("LieuRdv")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("pta_lieurdv");

                    b.Property<int>("PartenaireActiviteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pta_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartenaireActiviteId"));

                    b.Property<string>("TypeActivite")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("pta_typeactivite");

                    b.HasKey("PersonneId")
                        .HasName("pk_pta");

                    b.ToTable("t_e_partenaireactivite_pta");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.PartenaireCave", b =>
                {
                    b.Property<int>("PersonneId")
                        .HasColumnType("integer")
                        .HasColumnName("ptn_id");

                    b.Property<int>("PartenaireCaveId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ptc_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartenaireCaveId"));

                    b.Property<string>("TypeDegustation")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("ptc_typedegustation");

                    b.HasKey("PersonneId")
                        .HasName("pk_ptc");

                    b.ToTable("t_e_partenairecave_ptc");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.PartenaireHebergement", b =>
                {
                    b.Property<int>("PersonneId")
                        .HasColumnType("integer")
                        .HasColumnName("ptn_id");

                    b.Property<int?>("Etoiles")
                        .HasColumnType("integer")
                        .HasColumnName("pth_etoiles");

                    b.Property<int?>("NbChambre")
                        .HasColumnType("integer")
                        .HasColumnName("pth_nbchambre");

                    b.Property<int>("PartenaireHebergementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("pth_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartenaireHebergementId"));

                    b.Property<string>("TypeHebergement")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("pth_typehebergement");

                    b.HasKey("PersonneId")
                        .HasName("pk_pth");

                    b.ToTable("t_e_partenairehebergement_pth");

                    b.HasCheckConstraint("ck_pth_etoiles", "pth_etoiles between 0 and 5");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.PartenaireRestaurant", b =>
                {
                    b.Property<int>("PersonneId")
                        .HasColumnType("integer")
                        .HasColumnName("ptn_id");

                    b.Property<int?>("Etoiles")
                        .HasColumnType("integer")
                        .HasColumnName("ptr_etoiles");

                    b.Property<int>("PartenaireRestaurantId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("ptr_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PartenaireRestaurantId"));

                    b.Property<string>("Specialite")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ptr_specialite");

                    b.Property<string>("TypeCuisine")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("ptr_typecuisine");

                    b.HasKey("PersonneId")
                        .HasName("pk_ptr");

                    b.ToTable("t_e_partenairerestaurant_ptr");

                    b.HasCheckConstraint("ck_ptr_etoiles", "ptr_etoiles between 0 and 5");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Passe", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("integer")
                        .HasColumnName("rsv_id");

                    b.Property<int>("CommandeId")
                        .HasColumnType("integer")
                        .HasColumnName("cmd_id");

                    b.HasKey("ReservationId", "CommandeId")
                        .HasName("pk_pss");

                    b.HasIndex("CommandeId");

                    b.ToTable("t_j_passe_pss");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Paye", b =>
                {
                    b.Property<int>("ReservationId")
                        .HasColumnType("integer")
                        .HasColumnName("rsv_id");

                    b.Property<int>("TypePayementId")
                        .HasColumnType("integer")
                        .HasColumnName("tpa_id");

                    b.HasKey("ReservationId", "TypePayementId")
                        .HasName("pk_pay");

                    b.HasIndex("TypePayementId");

                    b.ToTable("t_j_paye_pay");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Personne", b =>
                {
                    b.Property<int>("PersonneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("prs_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("PersonneId"));

                    b.Property<string>("Mail")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prs_mail");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("prs_nom");

                    b.HasKey("PersonneId")
                        .HasName("pk_prs");

                    b.HasAlternateKey("Mail")
                        .HasName("uq_prs_mail");

                    b.ToTable("t_e_personne_prs");

                    b.HasCheckConstraint("ck_prs_mail", "prs_mail like '%@%.%'");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.RefCarteBancaire", b =>
                {
                    b.Property<int>("CarteId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rcb_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CarteId"));

                    b.Property<DateTime>("DateExpirationCarte")
                        .HasColumnType("date")
                        .HasColumnName("rcb_dateexpirationcarte");

                    b.Property<string>("NomCarte")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("rcb_nomcarte");

                    b.Property<string>("NumCarte")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("rcb_numcarte");

                    b.HasKey("CarteId")
                        .HasName("pk_rcb");

                    b.ToTable("t_e_refcartebancaire_rcb");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Reported", b =>
                {
                    b.Property<int>("AvisId")
                        .HasColumnType("integer")
                        .HasColumnName("avi_id");

                    b.Property<int>("PersonneId")
                        .HasColumnType("integer")
                        .HasColumnName("prs_id");

                    b.Property<bool>("A_Signale")
                        .HasColumnType("boolean")
                        .HasColumnName("rep_a_signale");

                    b.HasKey("AvisId", "PersonneId")
                        .HasName("pk_rep");

                    b.HasIndex("PersonneId");

                    b.ToTable("t_j_reported_rep");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rsv_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("BonCadeauId")
                        .HasColumnType("integer")
                        .HasColumnName("bcd_id");

                    b.Property<DateTime>("DateDebutResa")
                        .HasColumnType("date")
                        .HasColumnName("rsv_datedebutresa");

                    b.Property<DateTime>("DateFacture")
                        .HasColumnType("date")
                        .HasColumnName("rsv_datefacture");

                    b.Property<DateTime>("DateFinResa")
                        .HasColumnType("date")
                        .HasColumnName("rsv_datefinresa");

                    b.Property<int>("NbAdultes")
                        .HasColumnType("integer")
                        .HasColumnName("rsv_nbadultes");

                    b.Property<int>("NbChambres")
                        .HasColumnType("integer")
                        .HasColumnName("rsv_nbchambres");

                    b.Property<int>("NbEnfants")
                        .HasColumnType("integer")
                        .HasColumnName("rsv_nbenfants");

                    b.Property<decimal>("PrixTotal")
                        .HasColumnType("numeric(9,2)")
                        .HasColumnName("rsv_prixtotal");

                    b.Property<int>("SejourId")
                        .HasColumnType("integer")
                        .HasColumnName("sjr_id");

                    b.HasKey("ReservationId")
                        .HasName("pk_rsv");

                    b.HasIndex("BonCadeauId");

                    b.HasIndex("SejourId");

                    b.ToTable("t_e_reservation_rsv");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Reside", b =>
                {
                    b.Property<int>("AdresseId")
                        .HasColumnType("integer")
                        .HasColumnName("ads_id");

                    b.Property<int>("PersonneId")
                        .HasColumnType("integer")
                        .HasColumnName("prs_id");

                    b.HasKey("AdresseId", "PersonneId")
                        .HasName("pk_rsd");

                    b.HasIndex("PersonneId");

                    b.ToTable("t_j_reside_rsd");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.RouteDesVins", b =>
                {
                    b.Property<int>("RouteDesVinsId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("rdv_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RouteDesVinsId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("rdv_description");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("varchar(30)")
                        .HasColumnName("rdv_titre");

                    b.Property<int?>("VignobleId")
                        .HasColumnType("integer")
                        .HasColumnName("vgb_id");

                    b.HasKey("RouteDesVinsId")
                        .HasName("pk_rdv");

                    b.HasIndex("VignobleId");

                    b.ToTable("t_e_routedesvins_rdv");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Sejour", b =>
                {
                    b.Property<int>("SejourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("sjr_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("SejourId"));

                    b.Property<int>("CatSejourId")
                        .HasColumnType("integer")
                        .HasColumnName("csj_id");

                    b.Property<int?>("CatVignobleId")
                        .HasColumnType("integer")
                        .HasColumnName("cvg_id");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sjr_description");

                    b.Property<bool>("Est_Valide")
                        .HasColumnType("boolean")
                        .HasColumnName("sjr_est_valide");

                    b.Property<decimal>("NbJour")
                        .HasColumnType("numeric(3,2)")
                        .HasColumnName("sjr_nbjour");

                    b.Property<int>("NbNuit")
                        .HasColumnType("integer")
                        .HasColumnName("sjr_nbnuit");

                    b.Property<decimal>("Prix")
                        .HasColumnType("numeric(7,2)")
                        .HasColumnName("sjr_prix");

                    b.Property<int?>("Promotion")
                        .HasColumnType("integer")
                        .HasColumnName("sjr_promotion");

                    b.Property<int?>("RouteVinId")
                        .HasColumnType("integer")
                        .HasColumnName("rdv_id");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)")
                        .HasColumnName("sjr_titre");

                    b.HasKey("SejourId")
                        .HasName("pk_sjr");

                    b.HasIndex("CatSejourId");

                    b.HasIndex("CatVignobleId");

                    b.HasIndex("RouteVinId");

                    b.ToTable("t_e_sejour_sjr");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.SejourCadeau", b =>
                {
                    b.Property<int>("BonCadeauId")
                        .HasColumnType("integer")
                        .HasColumnName("bcd_id");

                    b.Property<string>("ChoixDestination")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sjc_choixdestination");

                    b.Property<int>("SejourId")
                        .HasColumnType("integer")
                        .HasColumnName("sjr_id");

                    b.HasKey("BonCadeauId")
                        .HasName("pk_sjc");

                    b.HasIndex("SejourId");

                    b.ToTable("t_e_sejourcadeau_sjc");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.TypeElementEtape", b =>
                {
                    b.Property<int>("TypeElementEtapeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tpe_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypeElementEtapeId"));

                    b.Property<string>("Libelle")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("tpe_libelle");

                    b.HasKey("TypeElementEtapeId")
                        .HasName("pk_tpe");

                    b.ToTable("t_e_typeelementetape_tpe");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.TypePayement", b =>
                {
                    b.Property<int>("TypePayementId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("tpa_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("TypePayementId"));

                    b.Property<string>("Libelle")
                        .HasColumnType("text")
                        .HasColumnName("tpa_libelle");

                    b.HasKey("TypePayementId")
                        .HasName("pk_tpa");

                    b.ToTable("t_e_typepayement_tpa");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.User", b =>
                {
                    b.Property<int>("PersonneId")
                        .HasColumnType("integer")
                        .HasColumnName("prs_id");

                    b.Property<DateTime>("DateConnexion")
                        .HasColumnType("date")
                        .HasColumnName("usr_dateconnexion");

                    b.Property<DateTime>("DateNaissance")
                        .HasColumnType("date")
                        .HasColumnName("usr_datenaissance");

                    b.Property<string>("Mdp")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("usr_mdp");

                    b.Property<bool>("Newsletter")
                        .HasColumnType("boolean")
                        .HasColumnName("usr_newsletter");

                    b.Property<string>("Prenom")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usr_prenom");

                    b.Property<string>("Pseudo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)")
                        .HasColumnName("usr_pseudo");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("usr_role");

                    b.Property<string>("Tel")
                        .HasColumnType("char(10)")
                        .HasColumnName("usr_tel");

                    b.Property<string>("Titre")
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)")
                        .HasColumnName("usr_titre");

                    b.HasKey("PersonneId")
                        .HasName("pk_usr");

                    b.HasAlternateKey("Pseudo")
                        .HasName("uq_usr_pseudo");

                    b.ToTable("t_e_user_usr");

                    b.HasCheckConstraint("ck_usr_datenaissance", "now() - usr_datenaissance > INTERVAL '6570 days'");

                    b.HasCheckConstraint("ck_usr_tel", "usr_tel like '06%' or usr_tel like '07%'");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Vignoble", b =>
                {
                    b.Property<int>("VignobleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("vgb_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("VignobleId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("vgb_description");

                    b.Property<int>("LienId")
                        .HasColumnType("integer")
                        .HasColumnName("len_id");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("vgb_titre");

                    b.HasKey("VignobleId")
                        .HasName("pk_vgb");

                    b.HasIndex("LienId");

                    b.ToTable("t_e_vignoble_vgb");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Avis", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Personne", "PersonneAvis")
                        .WithMany("AvisPersonne")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_avi_prs");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Sejour", "SejourAvis")
                        .WithMany("AvisSejour")
                        .HasForeignKey("SejourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_avi_sjr");

                    b.Navigation("PersonneAvis");

                    b.Navigation("SejourAvis");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.CatParticipant", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Lien", "LienCatParticipant")
                        .WithMany("CatParticipantLien")
                        .HasForeignKey("LienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cpp_len");

                    b.Navigation("LienCatParticipant");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.CatSejour", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Lien", "LienCatSejour")
                        .WithMany("CatSejourLien")
                        .HasForeignKey("LienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_csj_len");

                    b.Navigation("LienCatSejour");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.ChequeCadeau", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.BonCadeau", "BonCadeauChequeCadeau")
                        .WithMany("ChequeCadeauBonCadeau")
                        .HasForeignKey("BonCadeauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cqc_bcd");

                    b.Navigation("BonCadeauChequeCadeau");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Commande", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.User", "UserCommande")
                        .WithMany("CommandeUser")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cmd_cmp");

                    b.Navigation("UserCommande");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Comporte", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.CatParticipant", "CatParticipantComporte")
                        .WithMany("ComporteCatParticipant")
                        .HasForeignKey("CatParticipantId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cpt_cpp");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Sejour", "SejourComporte")
                        .WithMany("ComporteSejour")
                        .HasForeignKey("SejourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cpt_sjr");

                    b.Navigation("CatParticipantComporte");

                    b.Navigation("SejourComporte");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.CompteCarte", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.RefCarteBancaire", "RefCarteBancaireCompteCarte")
                        .WithMany("CompteCarteRefCarteBancaire")
                        .HasForeignKey("CarteId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cpc_rcb");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.User", "UserCompteCarte")
                        .WithMany("CompteCarteUser")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_cpc_cmp");

                    b.Navigation("RefCarteBancaireCompteCarte");

                    b.Navigation("UserCompteCarte");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Concerne", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.ElementEtape", "ElementEtapeConcerne")
                        .WithMany("ConcerneElementEtape")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ccr_ele");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Etape", "EtapeConcerne")
                        .WithMany("ConcerneEtape")
                        .HasForeignKey("EtapeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ccr_etp");

                    b.Navigation("ElementEtapeConcerne");

                    b.Navigation("EtapeConcerne");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Contient", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.ElementEtape", "ElementEtapeContient")
                        .WithMany("ContientElementEtape")
                        .HasForeignKey("ElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ctn_ele");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Lien", "LienContient")
                        .WithMany("ContientLien")
                        .HasForeignKey("LienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ctn_len");

                    b.Navigation("ElementEtapeContient");

                    b.Navigation("LienContient");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.ElementEtape", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Partenaire", "PartenaireElementEtape")
                        .WithMany("ElementsEtapePartenaire")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ele_ptn");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.TypeElementEtape", "TypeElementEtapeElementEtape")
                        .WithMany("ElementEtapeTypeElementEtape")
                        .HasForeignKey("TypeElementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_ele_tpe");

                    b.Navigation("PartenaireElementEtape");

                    b.Navigation("TypeElementEtapeElementEtape");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.ElementVignoble", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Vignoble", "VignobleElementVignoble")
                        .WithMany("ElementVignobleVignoble")
                        .HasForeignKey("VignobleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_evg_vgb");

                    b.Navigation("VignobleElementVignoble");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Est_facturee", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Adresse", "AdresseEst_facturee")
                        .WithMany("Est_factureeAdresse")
                        .HasForeignKey("AdresseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_efc_ads");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Reservation", "ReservationEst_facturee")
                        .WithMany("Est_factureeReservation")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_efc_rsv");

                    b.Navigation("AdresseEst_facturee");

                    b.Navigation("ReservationEst_facturee");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Etape", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Sejour", "SejourEtape")
                        .WithMany("EtapesSejour")
                        .HasForeignKey("SejourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_etp_sjr");

                    b.Navigation("SejourEtape");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Favori", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.User", "UserFavori")
                        .WithMany("FavoriUser")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fav_clt");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Sejour", "SejourFavori")
                        .WithMany("FavoriSejour")
                        .HasForeignKey("SejourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_fav_sjr");

                    b.Navigation("SejourFavori");

                    b.Navigation("UserFavori");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.HistoriqueCadeau", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.BonCadeau", "BonCadeauHistoriqueCadeau")
                        .WithMany("HistoriqueCadeauBonCadeau")
                        .HasForeignKey("BonCadeauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_htc_bcd");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.User", "UserHistoriqueCadeau")
                        .WithMany("HistoriqueCadeauUser")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_htc_clt");

                    b.Navigation("BonCadeauHistoriqueCadeau");

                    b.Navigation("UserHistoriqueCadeau");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.LienAvis", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Avis", "AvisLienAvis")
                        .WithMany("LiensAvisAvis")
                        .HasForeignKey("AvisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lav_avi");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Lien", "LienLienAvis")
                        .WithMany("LiensAvisLien")
                        .HasForeignKey("LienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lav_len");

                    b.Navigation("AvisLienAvis");

                    b.Navigation("LienLienAvis");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.LienElementVignoble", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.ElementVignoble", "ElementVignobleLienElementVignoble")
                        .WithMany("LienElementVignobleElementVignoble")
                        .HasForeignKey("ElementVignobleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lev_evg");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Lien", "LienLienElementVignoble")
                        .WithMany("LienElementVignobleLien")
                        .HasForeignKey("LienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lev_len");

                    b.Navigation("ElementVignobleLienElementVignoble");

                    b.Navigation("LienLienElementVignoble");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.LienEtape", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Etape", "EtapeLienEtape")
                        .WithMany("LienEtapeEtape")
                        .HasForeignKey("EtapeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lep_etp");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Lien", "LienLienEtape")
                        .WithMany("LienEtapeLien")
                        .HasForeignKey("LienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lep_len");

                    b.Navigation("EtapeLienEtape");

                    b.Navigation("LienLienEtape");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.LienRouteDesVins", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Lien", "LienLienRouteDesVins")
                        .WithMany("LienRouteDesVinsLien")
                        .HasForeignKey("LienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lrv_len");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.RouteDesVins", "RouteDesVinsLienRouteDesVins")
                        .WithMany("LienRouteDesVinsRouteDesVins")
                        .HasForeignKey("RouteDesVinsId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lrv_rdv");

                    b.Navigation("LienLienRouteDesVins");

                    b.Navigation("RouteDesVinsLienRouteDesVins");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.LienSejour", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Lien", "LienLienSejour")
                        .WithMany("LienSejourLien")
                        .HasForeignKey("LienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lsj_len");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Sejour", "SejourLienSejour")
                        .WithMany("LienSejourSejour")
                        .HasForeignKey("SejourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_lsj_sjr");

                    b.Navigation("LienLienSejour");

                    b.Navigation("SejourLienSejour");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Panier", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.User", "UserPanier")
                        .WithMany("PanierUser")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pnr_cmp");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Sejour", "SejourPanier")
                        .WithMany("PanierSejour")
                        .HasForeignKey("SejourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pnr_sjr");

                    b.Navigation("SejourPanier");

                    b.Navigation("UserPanier");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Partenaire", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Personne", "PersonnePartenaire")
                        .WithMany("PartenairePersonne")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ptn_prs");

                    b.Navigation("PersonnePartenaire");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.PartenaireActivite", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Partenaire", "PartenairePartenaireActivite")
                        .WithMany("PartenairesActivitePartenaire")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pta_ptn");

                    b.Navigation("PartenairePartenaireActivite");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.PartenaireCave", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Partenaire", "PartenairePartenaireCave")
                        .WithMany("PartenairesCavePartenaire")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ptc_ptn");

                    b.Navigation("PartenairePartenaireCave");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.PartenaireHebergement", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Partenaire", "PartenairePartenaireHebergement")
                        .WithMany("PartenairesHebergementPartenaire")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pth_ptn");

                    b.Navigation("PartenairePartenaireHebergement");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.PartenaireRestaurant", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Partenaire", "PartenairePartenaireRestaurant")
                        .WithMany("PartenairesRestaurantPartenaire")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_ptr_ptn");

                    b.Navigation("PartenairePartenaireRestaurant");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Passe", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Commande", "CommandePasse")
                        .WithMany("PasseCommande")
                        .HasForeignKey("CommandeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pss_cmd");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Reservation", "ReservationPasse")
                        .WithMany("PasseReservation")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pss_rsv");

                    b.Navigation("CommandePasse");

                    b.Navigation("ReservationPasse");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Paye", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Reservation", "ReservationPaye")
                        .WithMany("PayeReservation")
                        .HasForeignKey("ReservationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pay_rsv");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.TypePayement", "TypePayementPaye")
                        .WithMany("PayeTypePayement")
                        .HasForeignKey("TypePayementId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_pay_tpa");

                    b.Navigation("ReservationPaye");

                    b.Navigation("TypePayementPaye");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Reported", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Avis", "AvisReported")
                        .WithMany("ReportedAvis")
                        .HasForeignKey("AvisId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rep_avi");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.User", "UserReported")
                        .WithMany("ReportedUser")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rep_cmp");

                    b.Navigation("AvisReported");

                    b.Navigation("UserReported");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Reservation", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.BonCadeau", "BonCadeauReservation")
                        .WithMany("ReservationBonCadeau")
                        .HasForeignKey("BonCadeauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rsv_bcd");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Sejour", "SejourReservation")
                        .WithMany("ReservationsSejour")
                        .HasForeignKey("SejourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rsv_sjr");

                    b.Navigation("BonCadeauReservation");

                    b.Navigation("SejourReservation");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Reside", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Adresse", "AdresseReside")
                        .WithMany("ResideAdresse")
                        .HasForeignKey("AdresseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rsd_ads");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.User", "UserReside")
                        .WithMany("ResideUser")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_rsd_cmp");

                    b.Navigation("AdresseReside");

                    b.Navigation("UserReside");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.RouteDesVins", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Vignoble", "VignobleRouteDesVins")
                        .WithMany("RouteDesVinsVignoble")
                        .HasForeignKey("VignobleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_rdv_vgb");

                    b.Navigation("VignobleRouteDesVins");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Sejour", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.CatSejour", "SejourCatSejour")
                        .WithMany("CatSejoursSejour")
                        .HasForeignKey("CatSejourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sjr_csj");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.CatVignoble", "SejourCatVignoble")
                        .WithMany("CatVignobleSejour")
                        .HasForeignKey("CatVignobleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sjr_cvg");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.RouteDesVins", "RouteDesVinsSejour")
                        .WithMany("SejourRouteDesVins")
                        .HasForeignKey("RouteVinId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_sjr_rdv");

                    b.Navigation("RouteDesVinsSejour");

                    b.Navigation("SejourCatSejour");

                    b.Navigation("SejourCatVignoble");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.SejourCadeau", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.BonCadeau", "BonCadeauSejourCadeau")
                        .WithMany("SejourCadeauBonCadeau")
                        .HasForeignKey("BonCadeauId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sjc_bcd");

                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Sejour", "SejourSejourCadeau")
                        .WithMany("SejourCadeauSejour")
                        .HasForeignKey("SejourId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sjc_sjr");

                    b.Navigation("BonCadeauSejourCadeau");

                    b.Navigation("SejourSejourCadeau");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.User", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Personne", "PersonneUser")
                        .WithMany("UserPersonne")
                        .HasForeignKey("PersonneId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_usr_prs");

                    b.Navigation("PersonneUser");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Vignoble", b =>
                {
                    b.HasOne("WS_VINOTRIP.Models.EntityFramework.Lien", "LienVignoble")
                        .WithMany("VignobleLien")
                        .HasForeignKey("LienId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_vgb_len");

                    b.Navigation("LienVignoble");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Adresse", b =>
                {
                    b.Navigation("Est_factureeAdresse");

                    b.Navigation("ResideAdresse");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Avis", b =>
                {
                    b.Navigation("LiensAvisAvis");

                    b.Navigation("ReportedAvis");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.BonCadeau", b =>
                {
                    b.Navigation("ChequeCadeauBonCadeau");

                    b.Navigation("HistoriqueCadeauBonCadeau");

                    b.Navigation("ReservationBonCadeau");

                    b.Navigation("SejourCadeauBonCadeau");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.CatParticipant", b =>
                {
                    b.Navigation("ComporteCatParticipant");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.CatSejour", b =>
                {
                    b.Navigation("CatSejoursSejour");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.CatVignoble", b =>
                {
                    b.Navigation("CatVignobleSejour");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Commande", b =>
                {
                    b.Navigation("PasseCommande");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.ElementEtape", b =>
                {
                    b.Navigation("ConcerneElementEtape");

                    b.Navigation("ContientElementEtape");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.ElementVignoble", b =>
                {
                    b.Navigation("LienElementVignobleElementVignoble");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Etape", b =>
                {
                    b.Navigation("ConcerneEtape");

                    b.Navigation("LienEtapeEtape");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Lien", b =>
                {
                    b.Navigation("CatParticipantLien");

                    b.Navigation("CatSejourLien");

                    b.Navigation("ContientLien");

                    b.Navigation("LienElementVignobleLien");

                    b.Navigation("LienEtapeLien");

                    b.Navigation("LienRouteDesVinsLien");

                    b.Navigation("LienSejourLien");

                    b.Navigation("LiensAvisLien");

                    b.Navigation("VignobleLien");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Partenaire", b =>
                {
                    b.Navigation("ElementsEtapePartenaire");

                    b.Navigation("PartenairesActivitePartenaire");

                    b.Navigation("PartenairesCavePartenaire");

                    b.Navigation("PartenairesHebergementPartenaire");

                    b.Navigation("PartenairesRestaurantPartenaire");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Personne", b =>
                {
                    b.Navigation("AvisPersonne");

                    b.Navigation("PartenairePersonne");

                    b.Navigation("UserPersonne");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.RefCarteBancaire", b =>
                {
                    b.Navigation("CompteCarteRefCarteBancaire");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Reservation", b =>
                {
                    b.Navigation("Est_factureeReservation");

                    b.Navigation("PasseReservation");

                    b.Navigation("PayeReservation");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.RouteDesVins", b =>
                {
                    b.Navigation("LienRouteDesVinsRouteDesVins");

                    b.Navigation("SejourRouteDesVins");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Sejour", b =>
                {
                    b.Navigation("AvisSejour");

                    b.Navigation("ComporteSejour");

                    b.Navigation("EtapesSejour");

                    b.Navigation("FavoriSejour");

                    b.Navigation("LienSejourSejour");

                    b.Navigation("PanierSejour");

                    b.Navigation("ReservationsSejour");

                    b.Navigation("SejourCadeauSejour");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.TypeElementEtape", b =>
                {
                    b.Navigation("ElementEtapeTypeElementEtape");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.TypePayement", b =>
                {
                    b.Navigation("PayeTypePayement");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.User", b =>
                {
                    b.Navigation("CommandeUser");

                    b.Navigation("CompteCarteUser");

                    b.Navigation("FavoriUser");

                    b.Navigation("HistoriqueCadeauUser");

                    b.Navigation("PanierUser");

                    b.Navigation("ReportedUser");

                    b.Navigation("ResideUser");
                });

            modelBuilder.Entity("WS_VINOTRIP.Models.EntityFramework.Vignoble", b =>
                {
                    b.Navigation("ElementVignobleVignoble");

                    b.Navigation("RouteDesVinsVignoble");
                });
#pragma warning restore 612, 618
        }
    }
}
